added about and conduct pages
Python-Monthly/Python-Monthly-Website pull request #29
Opened 2016-10-23 00:23 UTC by tjadanel

I have created some place holder pages

- about

- Code of Conduct (using the django Code of conduct)

2016-10-23 00:26 UTC, tjadanel commented
This should address #23

2016-10-23 03:23 UTC, sgregg85 commented
The about page says that we meet at 9PM PST instead of EST, besides that, everything else looks good

2016-10-23 03:51 UTC, tjadanel commented
Fixed the time to 6PM/PST

2016-10-24 20:44 UTC, aculler requested changes
I didn't do an in-depth review of the HTML files since they're generated by Pelican. Just a few minor grammatical fixes and it'll be all set for merging.

2016-10-24 20:44 UTC, adc4392 commented on content/pages/about.md
> +Python Monthly is a online python community that meets every first Thursday of the month at 6PM/PST via the [Python Monthly YouTube Channel](https://www.youtube.com/channel/UC7ROIuBkGtLpCIMsgoIwv0Q).
Pretty sure Python is a proper noun and should be capitalized.

2016-10-24 20:44 UTC, adc4392 commented on content/pages/codeofconduct.md
> +* **Be careful in the words that you choose**: we are a community of professionals, and we conduct ourselves professionally. Be kind to others. Do not insult or put down other participants. Harassmen
Capitalize the first 'W'?

2016-10-24 20:48 UTC, merged